import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap/dist/js/bootstrap.bundle.min.js'
import 'admin-lte/dist/css/adminlte.min.css'
import 'admin-lte/dist/js/adminlte.min.js'
import 'admin-lte/plugins/jquery/jquery.min.js'
import '@fortawesome/fontawesome-free/css/all.css'
import '../assets/css/one-page-wonder.css'